### ISSUE TITLE
Documentation: allowed_origins format is wrong in examples

### ISSUE THREAD

**Issue by djozsef** [mezzio/mezzio-cors#18]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.0.3

#### Summary

Documentation examples hint that allowed origins shall be defined with hostnames or domains but the extension expexts URI strings in a [`fnmatch`](https://www.php.net/manual/en/function.fnmatch.php) pattern format. This is misleading and examples do not work.

#### Current behavior

Since documentation hints a wrong allowed origin URI format, extension does not work as expected.

#### How to reproduce

Use any simple domain as allowed origin, it will not match and will fall back to a 403 error.

#### Expected behavior

Either documentation should have examples with proper URL format.

**Comment by boesing** [comment]
@djozsef The documentation already contains the [hint](https://docs.mezzio.dev/mezzio-cors/v1/intro/) to the `fnmatch` detail but you are right, that we should mention this within the [middleware](https://docs.mezzio.dev/mezzio-cors/v1/middleware/) documentation aswell.

And you are totally right that the examples do not fit!
Gonna fix this.

**Comment by boesing** [comment]
Closed with #19
