### ISSUE TITLE
Issue with Psr\Http\Message\UriFactoryInterface using mezzio swoole

### ISSUE THREAD

**Issue by babarinde** [mezzio/mezzio-cors#8]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.0.1

#### Current behavior
While trying to use cors from installation page I see error below

`Unable to resolve service "Psr\Http\Message\UriFactoryInterface" to a factory; are you certain you provided it during configuration?`
triggered here https://github.com/mezzio/mezzio-cors/blob/1.1.x/src/Service/CorsFactory.php#L15
It seems one would have to specify a UriFactory mapped to this interface

**Comment by boesing** [comment]
Hello @babarinde,

You might want to upgrade `laminas/laminas-diactoros` to version 2.3.0. That version provides a `ConfigProvider` you need to register in your `config/config.php`.
After this, any PSR-17 factory should be registered and ready to use.

Please give us feedback here in case that this resolved your problem.

**Comment by babarinde** [comment]
Hello @boesing,
Thanks for your response.
This was resolved  by registering  `\Laminas\Diactoros\ConfigProvider::class` in  config/config.php as you mentioned as my project was already using 2.3.0 of `laminas/laminas-diactoros`.
It seems registering this ConfigProvider is not a default setting for mezzio, shouldn't the registration be part of the documentation?

**Comment by boesing** [comment]
I dont think thats necessary. 
With the latest `mezzio/mezzio-skeleton`, the config provider is added to the `config/config.php` by default.

This is probably an issue when upgrading from older versions of `laminas/laminas-diactoros` as the `laminas/laminas-component-installer` should add the config-provider automatically.

I've created a `laminas/laminas-component-installer` feature request to add `ConfigProvider` during an update process (currently only `install` works).
